#!/bin/sh
# Generic adapter: build a single always-on preamble any LLM can ingest,
# plus a projects/ dir the agent can @include on demand.
# Usage: ./adapters/generic.sh build [outdir]
set -eu

CORE="${CCB_HOME:-${HOME}/.context-config-builder}"
CMD="${1:-}"; OUT="${2:-$CORE/build}"

[ "$CMD" = "build" ] || { echo "usage: generic.sh build [outdir]" >&2; exit 2; }
[ -d "$CORE" ] || { echo "error: core not found at $CORE" >&2; exit 1; }

mkdir -p "$OUT/projects"

# Always-on preamble = concatenation of the always-on tier
{
  echo "# Agent Context Preamble (always-on)"
  echo "# Generated by context-config-builder generic adapter. Paste/attach this every session."
  echo
  for f in "$CORE"/always-on/*.md; do
    [ -e "$f" ] || continue
    echo "<!-- ===== $(basename "$f") ===== -->"
    cat "$f"; echo
  done
} > "$OUT/preamble.md"

# On-demand: copy project files verbatim (agent @includes when needed)
for f in "$CORE"/projects/*.md; do
  [ -e "$f" ] || continue
  cp "$f" "$OUT/projects/$(basename "$f")"
done

echo "Built:"
echo "  $OUT/preamble.md            (attach every session  -  the always-on tier)"
echo "  $OUT/projects/*.md          (attach on demand  -  the per-project tier)"
echo
echo "Usage with any LLM/agent: include preamble.md as system/context; when a task"
echo "touches a project, also include projects/<name>.md. This preserves the tiering."
