#!/bin/sh
# ccb-project-context.sh - agent-neutral (Model + Claude Code) project context, rule 18b parity.
#
# 1. INDEX: wraps project-steering-loader.sh. Both Model and Claude Code truncate large session-start
#    hook output to a short preview, so the full per-project dump silently never reached context.
#    The loader output is saved to one file per project and only a short index is printed.
# 2. REPO STEERING: Model auto-loads the launch repo's .kiro/steering/*.md in full; Claude Code does
#    not. For every active registry repo with .kiro/steering, keep a CLAUDE.local.md that @imports
#    those files (live, not copied), so Claude Code loads the same repo steering in full from the
#    same repo. CLAUDE.local.md is excluded via .git/info/exclude (local only, never committed).
#    Files marked inclusion: manual/fileMatch are skipped, as Model and the loader skip them.
set -u
K="$HOME/.kiro"
OUT="$K/context/projects"
REG="${CCK_REGISTRY:-$K/steering/context-registry.md}"
MARK="<!-- generated by ccb-project-context.sh (rule 18b); do not edit -->"

# --- 2. repo steering for Claude Code (idempotent; rewrites only when the import list changes) ---
sync_repo() {
  repo="$1"; [ -d "$repo/.kiro/steering" ] || return 0
  new="$MARK"
  for f in "$repo"/.kiro/steering/*.md; do
    [ -e "$f" ] || continue
    head -3 "$f" 2>/dev/null | grep -qiE 'inclusion:[[:space:]]*(manual|fileMatch)' && continue
    new="$new
@.kiro/steering/$(basename "$f")"
  done
  cur="$repo/CLAUDE.local.md"
  if [ -f "$cur" ] && ! head -1 "$cur" | grep -qF "$MARK"; then return 0; fi   # user-owned file: leave it
  [ "$(cat "$cur" 2>/dev/null)" = "$new" ] || printf '%s\n' "$new" > "$cur"
  ex="$repo/.git/info/exclude"
  [ -f "$ex" ] && ! grep -qx 'CLAUDE.local.md' "$ex" && echo 'CLAUDE.local.md' >> "$ex"
  return 0
}
if [ -f "$REG" ]; then
  grep -E '^\| *\[x\]' "$REG" | while IFS='|' read -r _ mk nm og cx rp rest; do
    p=$(printf '%s' "$rp" | sed 's/^ *//;s/ *$//'); [ -n "$p" ] || continue
    case "$p" in /*) full="$p";; Projects/*) full="$HOME/$p";; *) full="$HOME/Projects/$p";; esac
    sync_repo "$full"
  done
fi

# --- 1. index (run the loader from $HOME with the launch repo passed explicitly, so its cwd
#        double-load guard does not hide the launch repo from Claude Code) ---
mkdir -p "$OUT"
rm -f "$OUT"/*.md
root=$(git rev-parse --show-toplevel 2>/dev/null || true)
( cd "$HOME" && CCK_ACTIVE_PROJECT="$root" "$K/hooks/project-steering-loader.sh" ) 2>/dev/null | awk -v out="$OUT" '
  /^=== PROJECT CONTEXT: / { p=$4; n=p; sub(/.*\//,"",n); f=out"/"n".md"; print "- " p " -> " f; next }
  /^\(project-steering-loader:/ { print "  " $0; next }
  f { print > f }
' > "$OUT/.index"
if [ -s "$OUT/.index" ]; then
  echo "[ccb-project-context] per-project steering saved (read the matching file when a task touches that project):"
  cat "$OUT/.index"
else
  echo "[ccb-project-context] no project steering emitted for this launch dir."
fi
[ -n "$root" ] && [ -d "$root/.kiro/steering" ] && echo "[ccb-project-context] launch repo steering loads in full natively (Model: workspace steering; Claude Code: CLAUDE.local.md)."
# --- 3. project tasks + advisor recommendations (rules 6c/18c): read when opening a project ---
NOTES="$K/hooks/agent-notes.sh"
if [ -x "$NOTES" ]; then
  if [ -n "$root" ] && [ -d "$root/.agent" ]; then
    items=$("$NOTES" show "$root" 2>/dev/null)
    echo "[agent-notes] $(basename "$root") open tasks/recommendations (read $root/.agent/ before working):"
    [ -n "$items" ] && echo "$items" || echo "  none open"
  elif [ -z "$root" ] && [ -f "$REG" ]; then
    grep -E '^\| *\[x\]' "$REG" | while IFS='|' read -r _ mk nm og cx rp rest; do
      p=$(printf '%s' "$rp" | sed 's/^ *//;s/ *$//'); [ -n "$p" ] || continue
      case "$p" in /*) full="$p";; Projects/*) full="$HOME/$p";; *) full="$HOME/Projects/$p";; esac
      [ -d "$full/.agent" ] || continue
      n=$("$NOTES" show "$full" 2>/dev/null | wc -l | tr -d ' ')
      [ "$n" -gt 0 ] && echo "[agent-notes] $(basename "$full"): $n open (read $full/.agent/ when a task touches it)"
    done
  fi
fi
exit 0
